variables:
- name: app_default_directory
  value: sela_week7 
- name: ansible_directory
  value: ansible 
- name: init_host_ip
  value: 10.0.0.4
parameters:
- name: hosts
  type: object
  default:
  - 10.0.0.4
  - 10.0.0.5
  - 10.0.0.7

resources:
  repositories:
  - repository: AnsibleRepo # The name used to reference this repository in the checkout step
    type: github
    endpoint: ItaiGafny
    name: ItaiGafny/Sela-Week7-Ansible

trigger:
- master

stages:
 - stage: Build
   jobs:
    - job: Build
      displayName: Build
      pool:
      #removed, cannot run the packages needed: npm WARN deprecated @hapi/teamwork@4.0.0: This version has been deprecated and is no longer supported or maintained
      #vmImage: ubuntu-latest
        name: 'my-pool'

      steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '14.x'
        displayName: 'Install Node.js'

      - script: |
          npm install @hapi/hapi@19 @hapi/bell@12 @hapi/boom@9 @hapi/cookie@11 @hapi/inert@6 @hapi/joi@17 @hapi/vision@6 dotenv@8 ejs@3 postgres@1
          npm --save-dev nodemon@2
        displayName: 'npm install and build'

      - task: ArchiveFiles@2
        displayName: 'Archive files'
        inputs:
          rootFolderOrFile: '$(Build.SourcesDirectory)'
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          replaceExistingArchive: true
      - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        artifact: drop

      
      
 - stage: Deploy_to_Staging
   jobs:
    - job: Deploy
      displayName: Deploy
    - deployment: VMDeploy
      displayName: web
      variables:
      - name: LB_IP
        value: 20.119.109.101 
      - name: OKTA_ORG_URL
        value: dev-90664005.okta.com 

      environment:
        name:  'Staging'
        resourceType: VirtualMachine
        tags: 'staging'
      strategy:
      # default deployment strategy, more coming...
        runOnce:
          deploy:
            steps:
            - script: rm -rf ~/$(app_default_directory)
              displayName: Remove app
            - script: mkdir -p ~/$(app_default_directory)/$(ansible_directory)/files/app
              displayName: Make directory app to ansible files directory
            - checkout: AnsibleRepo
              displayName: Download ansible files

            - script: cp -R $(System.DefaultWorkingDirectory)/. ~/$(app_default_directory)/$(ansible_directory)
              displayName: Copy ansible files
            - ${{ each value in parameters.hosts }}:
              - script: echo ${{ value }} >> inventory
            - script: |
                echo [webservers1] >> ~/$(app_default_directory)/$(ansible_directory)/inventory
                cat inventory >>  ~/$(app_default_directory)/$(ansible_directory)/inventory
              displayName: Create hosts file 
            - script: unzip $(System.ArtifactsDirectory)/../drop/$(Build.BuildId).zip -d ~/$(app_default_directory)/$(ansible_directory)/files/app
              displayName: Unzip app to ansible files directory

            - task: replacetokens@5
              displayName: Create .env file with secret and regular params
              inputs:
                rootDirectory: /home/azureuser/sela_week7/ansible/files/app/ #bug that does not accept relative path?
                targetFiles: '.env.sample => .env'
                encoding: 'auto'
                tokenPattern: 'default'
                writeBOM: true
                actionOnMissing: 'warn'
                keepToken: false
                actionOnNoFiles: 'continue'
                enableTransforms: false
                enableRecursion: false
                useLegacyPattern: false
                enableTelemetry: true

            - script: |
                cat ~/$(app_default_directory)/$(ansible_directory)/files/app/.env
                ls -la  ~/$(app_default_directory)/$(ansible_directory)/files/app
              displayName: Show the new .env file

            #- script: zip -m ~/$(app_default_directory)/$(ansible_directory)/files/app/$(Build.BuildId).zip ~/$(app_default_directory)/$(ansible_directory)/files/app 
            - script: zip -r ~/$(app_default_directory)/$(ansible_directory)/files/app/$(Build.BuildId).zip ~/$(app_default_directory)/$(ansible_directory)/files/app 
              displayName: Zip back to save time the app to ansible files directory
            #- script: cp $(System.ArtifactsDirectory)/../drop/$(Build.BuildId).zip -d ~/$(app_default_directory)/$(ansible_directory)/files/app
            #  displayName: Copy Zipped app to Ansible files directory

            - script: |
                cd ~/$(app_default_directory)/$(ansible_directory)
                ansible-playbook ./install_site.yml --extra-vars "build_id=$(Build.BuildId) init_host_ip=$(init_host_ip)" 
              displayName: Run the Ansible playbook


